version: '2'

services:

  config:
    image: docker.appiness.mobi/spott-${DEPLOY_ENV}-website-config
    container_name: spott.website.config
    volumes:
      - configData:/var/lib/appiness
  seoserver:
    image: docker.appiness.mobi/spott.website.seoserver
    container_name: spott.website.seoserver
    ports:
      - 4000:4000
    depends_on:
      - config
    volumes_from:
      - config
  web:
    image: ${appiness.docker.registry}/spott.website:${project.version}
    container_name: spott.website
    ports:
      - 80:80
      - 443:443
    depends_on:
      - config
      - seoserver
    volumes_from:
      - config
volumes:
  configData:
